version: '3.8'

services:

  influxdb:
    image: influxdb:1.8.10
    ports:
      - '8087:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    networks:
      - common-network
  mqtt-broker:
    image: eclipse-mosquitto:latest
    ports:
      - "1884:1883"
      - "8085:8085"

    networks:
      - common-network
    volumes:
      - ./weatherStation/mosquitto.conf:/mosquitto/config/mosquitto.conf

  mongo:
    volumes:
      - weather_db:/data/db
    image: mongo:latest
    ports:
      - "27018:27017"
    networks:
      - common-network

  weather-station:
    build: ./weatherStation
    environment:
      - MQTT_BROKER_ADDRESS=mqtt-broker
      - MQTT_BROKER_PORT=1883
      - MQTT_TOPIC=weather_data
    depends_on:
      - mqtt-broker
    networks:
      - common-network

  weather-api:
    build: ./backend
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - influxdb
      - mongo
      - mqtt-broker
      - weather-station
    networks:
      - common-network
    environment:
      - DB_URI=mongodb://mongo:27017/weather
      - PORT=3000
      - JWT_SECRET=weather_app
      - MQTT_URL=mqtt://mqtt-broker:1883
      - MQTT_TOPIC=weather_data
      - INFLUX_URL=influxdb
      - INFLUX_PORT=8086
      - MODE=DEV

  weather-ui:
    depends_on:
      - weather-api
    build: ./frontend
    ports:
      - 8080:8080
    networks:
      - common-network
    environment:
      - VUE_APP_BACKEND_URL=http://localhost:3000
      - VUE_APP_MQTT_URL="ws://localhost:8085"
      - VUE_APP_MQTT_TOPIC="weather_data"

volumes:
  weather_db:
  influxdb-storage:

networks:
  common-network:
    driver: bridge
